services:
  app:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    build:
      context: ./docker/php
      args:
        PHP_UID: ${PHP_UID:-1000}
        PHP_GID: ${PHP_GID:-1000}
        INSTALL_SQLSRV: "true"          # necesitamos drivers para Azure SQL
        INSTALL_XDEBUG: ${INSTALL_XDEBUG:-false}
    container_name: php-app
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT:-9003}
      DB_SERVER: ${DB_SERVER}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ENCRYPT_PASSWORD_KEY: ${ENCRYPT_PASSWORD_KEY}
      NOREPLY_MAIL_PASSWORD: ${NOREPLY_MAIL_PASSWORD}
      SAS_TOKEN: ${SAS_TOKEN}

  web:
    image: nginx:1.27-alpine
    container_name: web
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
