version: '3.8'

services:
  php:
    build: .
    platform: linux/amd64
    container_name: php_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    env_file:
      - .env

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "Traace2014"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
